@startuml

skinparam classAttributeFontName Monospaced
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #D8D8D8
skinparam packageBorderColor #BDBDBD
skinparam classArrowColor #0B615E
skinparam shadowing false

'skinparam monochrome true
'skinparam nodesep 100
'skinparam ranksep 100
'note "All <color:black><b> (M)odels</b></color> extends <b>pyoko.Model</b> class" as N #orchid
title
<size:24>Entity Based Model Diagram</size>
( All Models extends <b>pyoko.Model</b> class )
endtitle
'legend left
'n..*     n or more instances
'n..m    Min n, Max m instances
'endlegend

' field_name            field_type     null blank
'                                      _ = True
'                                      * * = False

class Okutman<<(M,orchid)>>{
ad                    String  * *
soyad                 String  * *
tckn                  String
dogum_tarihi          String
dogum_yeri            String
tip                   String  * *
ucret                 String
uyruk                 String
medeni_hali           String
ikamet_adresi         String
telefon_no            String
oda_no                String  * *
oda_tel_no            String  * *
e_posta               String  * *
kan_grubu             String
fakulte               String  * *
ehliyet               String
bolum                 String  * *
akademik_yayinlari    String  * *
verdigi_dersler       String  * *
--
note: non-employee (guest) lecturers data
will be stored here
--
calisan               Personel()  * *
}

class Program<<(M,orchid)>>{
bolum                                String        * *
ucret                                Int
yil                                  String        * *
donem                                Int           * *
adi                                  String        * *
tanim                                String        * *
yeterlilik_kosullari_aciklamasi      String        * *
program_ciktilari                    String
mezuniyet_kosullari                  String        * *
kabul_kosullari                      String        * *
--
bolum_baskani                        Role()        * *
ects_bolum_kordinator                Role()        * *
akademik_kordinator                  Role()        * *
birim                                Birim()       * *
donem                                Donem()       * *

}
class Derslik<<(M,orchid)>>{
kod                                  String        * *
bina                                 String
tur                                  String
kapasite                             String        * *

--
dersler                              Sube()        * *
}

class Sube<<(M,orchid)>>{
ad                                   String             * *
kod                                  String             * *
donem                                String             * *
kontenjan                            Int                * *
--
okutman                              Okutman()          * *
ana_ders                             Ders()             * *
ogrenci                              Ogrenci()          * *
ders_devamsizligi                    DersDevamsizligi() * *
}

class Ders<<(M,orchid)>>{
ad                                   String  * *
kod                                  String  * *
kredi                                String  * *
zorunlu                              Boolean * *
akts_teori                           Float
akts_uygulama                        Float
donem                                Int     * *
ders_dili                            String  * *
verilis_bicimi                       Int     * *
--
program                              Program() * *
sube                                 Sube()    * *
donem                                Donem()   * *
--
**Degerlendirme(ListNode)**
|_ tur                               String
|_ toplam_puana_etki_yuzdesi         Int     * *

note: tur, final, arasinav,
tekders, butunleme, odev vb.
}


class Sinav <<(M,orchid)>> {
tarih                                Date             * *
yapilacagi_yer                       String           * *
tur                                  String
aciklama                             String
--
degerlendirme                        Degerlendirme()  * *
sube                                 Sube()           * *
}


class Ogrenci <<(M,orchid)>> {
ad                                   String             * *
soyad                                String             * *
ikamet_adresi                        String
tckn                                 String
dogum_tarihi                         Date
dogum_yeri                           String
uyruk                                String
medeni_hali                          String
ehliyet                              String
giris_tarihi                         Date               * *
mezuniyet_tarihi                     Date
bolum                                String             * *
fakulte                              String             * *
e_posta                              String             * *
ogrenci_no                           Int                * *
tel_no                               Int
akademik_yil                         String             * *
donem                                String             * *
kan_grubu                            String
basari_durumu                        String
ilisik_kesme                         String
hazırlık_durumu                      Boolean            * *
belge_basvurusu                      String
devamsizlik_durumu                   String             * *
--
ders_programi                        DersProgrami()     * *
rol                                  Role()             * *
ders_devamsizligi                    DersDevamsizligi() * *

--
**Dersler(ListNode)**
ders                               Sube()
}

class DersProgrami<<(M,orchid)>> {
gun                                String      * *
saat                               String      * *
--
sube                               Sube()      * *
derslik                            Derslik()   * *
}


class DersDevamsizligi <<(M,orchid)>> {
katilim_durumu                     Int            * *
--
ders                               Sube()         * *
ogrenci                            Ogrenci()      * *
}

class Borc <<(M,orchid)>> {
miktar                             Float           * *
yil                                Int             * *
odeme_turu                         String          * *
son_odeme_tarihi                   Date            * *
odeme_tarihi                       Date            * *
aciklama                           String
para_birimi                        String          * *
odenen_miktar                      String          * *
kalan_bakiye                       String
durum                              Boolean         * *
--
ogrenci                            Ogrenci()       * *
donem                              Donem()         * *
}

class Not <<(M,orchid)>> {
puan                               Int             * *
aciklama                           String
--
sinav                              Sinav()         * *
ogrenci                            Ogrenci()       * *

}

class Donem <<(M,orchid)>> {
baslangic_tarihi                   Date            * *
bitis_tarihi                       Date            * *
ad                                 String          * *
ucret                              Int
--
program                            Program()       * *
}


DersProgrami "1" -- "0..*" Derslik
DersProgrami "1" -- "0..*" Sube
Sinav "1" -- "0..*" Sube

Sube "0..*" -- "1" Okutman
Sube "0..*" -- "1" Ogrenci

Ders "1" --  "1" Program
Ders "1" -- "0..*" Sube
Ders "1" -- "0..*" Donem

Program "1" -- "1" Birim
Ogrenci "1" -- "0..*" DersDevamsizligi
Sube "1" -- "0..*" DersDevamsizligi
Program "1"-- "0..*" Donem

Not "1" -- "0..*" Ogrenci
Not "1"-- "0..*" Sinav

@enduml
